# ============================================================
# Library imports
# ============================================================
# Import core libraries for data acquisition, numerical
# computation, and visualization
from jqdatasdk import *
import datetime
import pandas as pd
from datetime import datetime
import numpy as np
import matplotlib.pyplot as plt

# Authenticate with JQData (used for market data retrieval)
auth('*','*')

# Set global plotting style
plt.rcParams.update({'figure.figsize': (16, 8), 'figure.dpi': 120})

# ============================================================
# Annualized return comparison of major equity indices
# ============================================================
# Retrieve daily price data for major Chinese equity indices.
# These indices serve as market benchmarks and reference
# underlyings for structured products such as Snowball notes.

SSEC = get_price(
    '000001.XSHG',
    start_date='2021-12-06',
    end_date='2022-12-06',
    frequency='daily',
    fields=None,
    skip_paused=False,
    fq='none'
)

SSEC50 = get_price(
    '000016.XSHG',
    start_date='2021-12-06',
    end_date='2022-12-06',
    frequency='daily',
    fields=None,
    skip_paused=False,
    fq='none'
)

CSI = get_price(
    '000300.XSHG',
    start_date='2021-12-06',
    end_date='2022-12-06',
    frequency='daily',
    fields=None,
    skip_paused=False,
    fq='none'
)

AS = get_price(
    '000002.XSHG',
    start_date='2021-12-06',
    end_date='2022-12-06',
    frequency='daily',
    fields=None,
    skip_paused=False,
    fq='none'
)

IC = get_price(
    '000905.XSHG',
    start_date='2021-12-06',
    end_date='2022-12-06',
    frequency='daily',
    fields=None,
    skip_paused=False,
    fq='none'
)

# ============================================================
# Construct annualized log returns
# ============================================================
# Compute daily log returns and annualize them assuming
# 252 trading days per year. Annualized returns provide
# a standardized performance comparison across indices.

Index_R = pd.DataFrame()
Index_R['SSEC'] = SSEC['close']
Index_R['SSEC50'] = SSEC50['close']
Index_R['CSI'] = CSI['close']
Index_R['AS'] = AS['close']
Index_R['IC'] = IC['close']

Index_R['SSEC_y_R'] = np.log(Index_R['SSEC'].pct_change() + 1) * np.sqrt(252)
Index_R['SSEC50_y_R'] = np.log(Index_R['SSEC50'].pct_change() + 1) * np.sqrt(252)
Index_R['CSI_y_R'] = np.log(Index_R['CSI'].pct_change() + 1) * np.sqrt(252)
Index_R['AS_y_R'] = np.log(Index_R['AS'].pct_change() + 1) * np.sqrt(252)
Index_R['IC_y_R'] = np.log(Index_R['IC'].pct_change() + 1) * np.sqrt(252)

# Replace missing values generated by differencing
Index_R.fillna(0, inplace=True)

# Retain only annualized return series
Index_R_y = Index_R[
    ['SSEC_y_R', 'SSEC50_y_R', 'CSI_y_R', 'AS_y_R', 'IC_y_R']
]

# Summary statistics of annualized returns
Index_R_y.describe(include='all')

# ============================================================
# Visualization of annualized index returns
# ============================================================
# Plot annualized returns to visually compare performance
# across different market indices.

Index_R_y.plot(
    title='Annualized Return of Main Indices',
    fontsize=10
)

# Reference line (e.g., coupon or hurdle rate commonly seen
# in Snowball products)
plt.axhline(y=0.175, color='b', linestyle='-.')

# Save figure for reporting or documentation
plt.savefig(
    r'C:\Users\Mory\FEdata\return.jpg',
    bbox_inches='tight'
)

# ============================================================
# Observation date setup (commented out)
# ============================================================
# This section is reserved for defining observation dates
# used in knock-out / knock-in evaluation of Snowball products.

# df = pd.date_range(start='2023-03-07', end='2024-06-07', freq='D')
# specific_dates = ['2023-03-07', ...]
